# Generated by Django 3.2.3 on 2021-05-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_auto_20210518_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
