# Generated by Django 3.1.7 on 2021-06-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_auto_20210523_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
