# Generated by Django 3.1.7 on 2021-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='/default_profile_pic.jpg', upload_to=''),
        ),
    ]
