# Generated by Django 3.2.3 on 2021-05-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_rate_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
