# Generated by Django 3.2 on 2021-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='square_feet',
            field=models.DecimalField(decimal_places=2, max_digits=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='baths',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
