# Generated by Django 3.1.7 on 2021-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210516_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rent_agreement',
            field=models.FileField(default='/Tenancy_Agreement.docx', upload_to=''),
        ),
    ]
