# Generated by Django 3.2.3 on 2021-06-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_6',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Both', 'Both')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='no_of_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent_agreement',
            field=models.FileField(blank=True, default='/Tenancy_Agreement.docx', upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='total_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
