# Generated by Django 3.2.3 on 2021-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210601_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Both', 'Both')], max_length=100),
        ),
    ]
