# Generated by Django 3.2.3 on 2021-06-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Both', 'Both'), ('Boys', 'Boys')], max_length=100),
        ),
    ]
