# Generated by Django 3.2.3 on 2021-06-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Both', 'Both'), ('Boys', 'Boys'), ('Girls', 'Girls')], max_length=100),
        ),
    ]
