# Generated by Django 3.2.3 on 2021-06-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Canal Road', 'Canal Road'), ('DHA', 'DHA'), ('Gulberg', 'Gulberg'), ('Ferozpur Road', 'Ferozpur Road'), ('Ichra', 'Ichra'), ('Johar Town', 'Johar Town'), ('Mall Road', 'Mall Road'), ('Behria Town', 'Behria Town'), ('Thokar', 'Thokar'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Cantt', 'Cantt'), ('Wapda Town', 'Wapda Town'), ('Iqbal Town', 'Iqbal Town'), ('Askari', 'Askari'), ('Valencia Town', 'Valencia Town'), ('Township', 'Township'), ('Sadar', 'Sadar'), ('Central Park', 'Central Park'), ('Jalo', 'Jalo'), ('Model Town', 'Model Town')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Both', 'Both')], max_length=100),
        ),
    ]
