# Generated by Django 3.2.3 on 2021-06-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20210622_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Mall Road', 'Mall Road'), ('Cantt', 'Cantt'), ('Valencia Town', 'Valencia Town'), ('Canal Road', 'Canal Road'), ('Ferozpur Road', 'Ferozpur Road'), ('Johar Town', 'Johar Town'), ('Sadar', 'Sadar'), ('Thokar', 'Thokar'), ('Model Town', 'Model Town'), ('Township', 'Township'), ('Jalo', 'Jalo'), ('Central Park', 'Central Park'), ('Gulberg', 'Gulberg'), ('Ichra', 'Ichra'), ('Behria Town', 'Behria Town'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Wapda Town', 'Wapda Town'), ('Iqbal Town', 'Iqbal Town'), ('Askari', 'Askari'), ('DHA', 'DHA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Both', 'Both'), ('Boys', 'Boys')], max_length=100),
        ),
    ]
