# Generated by Django 3.2.3 on 2021-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20210622_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Mall Road', 'Mall Road'), ('Township', 'Township'), ('Canal Road', 'Canal Road'), ('Valencia Town', 'Valencia Town'), ('Model Town', 'Model Town'), ('Sadar', 'Sadar'), ('DHA', 'DHA'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Cantt', 'Cantt'), ('Ferozpur Road', 'Ferozpur Road'), ('Iqbal Town', 'Iqbal Town'), ('Thokar', 'Thokar'), ('Behria Town', 'Behria Town'), ('Wapda Town', 'Wapda Town'), ('Gulberg', 'Gulberg'), ('Ichra', 'Ichra'), ('Askari', 'Askari'), ('Central Park', 'Central Park'), ('Johar Town', 'Johar Town'), ('Jalo', 'Jalo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Both', 'Both'), ('Boys', 'Boys'), ('Girls', 'Girls')], max_length=100),
        ),
    ]
