# Generated by Django 3.2.3 on 2021-08-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20210622_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Cantt', 'Cantt'), ('Iqbal Town', 'Iqbal Town'), ('Askari', 'Askari'), ('DHA', 'DHA'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Ferozpur Road', 'Ferozpur Road'), ('Jalo', 'Jalo'), ('Thokar', 'Thokar'), ('Behria Town', 'Behria Town'), ('Mall Road', 'Mall Road'), ('Gulberg', 'Gulberg'), ('Sadar', 'Sadar'), ('Township', 'Township'), ('Model Town', 'Model Town'), ('Ichra', 'Ichra'), ('Johar Town', 'Johar Town'), ('Canal Road', 'Canal Road'), ('Central Park', 'Central Park'), ('Valencia Town', 'Valencia Town'), ('Wapda Town', 'Wapda Town')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Both', 'Both')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Lahore', 'Lahore')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent_agreement',
            field=models.FileField(blank=True, default='/Tenancy_Agreement.pdf', upload_to=''),
        ),
    ]
