# Generated by Django 3.2.3 on 2021-08-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20210806_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Lakshmi Chock', 'Lakshmi Chock'), ('Wapda Town', 'Wapda Town'), ('Model Town', 'Model Town'), ('Mall Road', 'Mall Road'), ('Sadar', 'Sadar'), ('Iqbal Town', 'Iqbal Town'), ('Askari', 'Askari'), ('DHA', 'DHA'), ('Central Park', 'Central Park'), ('Jalo', 'Jalo'), ('Ferozpur Road', 'Ferozpur Road'), ('Gulberg', 'Gulberg'), ('Cantt', 'Cantt'), ('Township', 'Township'), ('Johar Town', 'Johar Town'), ('Ichra', 'Ichra'), ('Behria Town', 'Behria Town'), ('Thokar', 'Thokar'), ('Canal Road', 'Canal Road'), ('Valencia Town', 'Valencia Town')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Both', 'Both'), ('Girls', 'Girls'), ('Boys', 'Boys')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent_agreement',
            field=models.FileField(blank=True, default='/Tenancy_Agreement.docx', upload_to=''),
        ),
    ]
