# Generated by Django 3.2.3 on 2021-08-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20210806_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Luxury_category',
            field=models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Luxury', 'Luxury'), ('Gulberg', 'Gulberg')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Johar Town', 'Johar Town'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Cantt', 'Cantt'), ('Model Town', 'Model Town'), ('DHA', 'DHA'), ('Iqbal Town', 'Iqbal Town'), ('Central Park', 'Central Park'), ('Ichra', 'Ichra'), ('Jalo', 'Jalo'), ('Valencia Town', 'Valencia Town'), ('Behria Town', 'Behria Town'), ('Thokar', 'Thokar'), ('Askari', 'Askari'), ('Township', 'Township'), ('Gulberg', 'Gulberg'), ('Wapda Town', 'Wapda Town'), ('Sadar', 'Sadar'), ('Mall Road', 'Mall Road'), ('Ferozpur Road', 'Ferozpur Road'), ('Canal Road', 'Canal Road')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Both', 'Both')], max_length=100),
        ),
    ]
