# Generated by Django 3.2.3 on 2021-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20210806_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Luxury_category',
        ),
        migrations.AddField(
            model_name='listing',
            name='Luxury_Category',
            field=models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Luxury', 'Luxury')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Behria Town', 'Behria Town'), ('Model Town', 'Model Town'), ('Cantt', 'Cantt'), ('DHA', 'DHA'), ('Iqbal Town', 'Iqbal Town'), ('Ferozpur Road', 'Ferozpur Road'), ('Canal Road', 'Canal Road'), ('Jalo', 'Jalo'), ('Gulberg', 'Gulberg'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Sadar', 'Sadar'), ('Askari', 'Askari'), ('Johar Town', 'Johar Town'), ('Township', 'Township'), ('Ichra', 'Ichra'), ('Thokar', 'Thokar'), ('Wapda Town', 'Wapda Town'), ('Mall Road', 'Mall Road'), ('Central Park', 'Central Park'), ('Valencia Town', 'Valencia Town')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Both', 'Both')], max_length=100),
        ),
    ]
