# Generated by Django 3.2.3 on 2021-08-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_auto_20210806_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Luxury_Category',
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, choices=[('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Gold', 'Gold')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Gulberg', 'Gulberg'), ('Model Town', 'Model Town'), ('Behria Town', 'Behria Town'), ('Jalo', 'Jalo'), ('Cantt', 'Cantt'), ('DHA', 'DHA'), ('Ichra', 'Ichra'), ('Mall Road', 'Mall Road'), ('Township', 'Township'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Sadar', 'Sadar'), ('Iqbal Town', 'Iqbal Town'), ('Thokar', 'Thokar'), ('Askari', 'Askari'), ('Valencia Town', 'Valencia Town'), ('Canal Road', 'Canal Road'), ('Central Park', 'Central Park'), ('Johar Town', 'Johar Town'), ('Wapda Town', 'Wapda Town'), ('Ferozpur Road', 'Ferozpur Road')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
