# Generated by Django 3.2.3 on 2021-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_auto_20210806_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Model Town', 'Model Town'), ('Ferozpur Road', 'Ferozpur Road'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Central Park', 'Central Park'), ('Gulberg', 'Gulberg'), ('Canal Road', 'Canal Road'), ('Askari', 'Askari'), ('Thokar', 'Thokar'), ('Township', 'Township'), ('Cantt', 'Cantt'), ('Sadar', 'Sadar'), ('Behria Town', 'Behria Town'), ('Mall Road', 'Mall Road'), ('Johar Town', 'Johar Town'), ('Jalo', 'Jalo'), ('Iqbal Town', 'Iqbal Town'), ('Ichra', 'Ichra'), ('Wapda Town', 'Wapda Town'), ('Valencia Town', 'Valencia Town'), ('DHA', 'DHA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Both', 'Both'), ('Boys', 'Boys'), ('Girls', 'Girls')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond')], max_length=100),
        ),
    ]
