# Generated by Django 3.2.3 on 2021-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_auto_20210806_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Township', 'Township'), ('Mall Road', 'Mall Road'), ('Valencia Town', 'Valencia Town'), ('Central Park', 'Central Park'), ('Ferozpur Road', 'Ferozpur Road'), ('Thokar', 'Thokar'), ('Iqbal Town', 'Iqbal Town'), ('DHA', 'DHA'), ('Sadar', 'Sadar'), ('Cantt', 'Cantt'), ('Jalo', 'Jalo'), ('Gulberg', 'Gulberg'), ('Behria Town', 'Behria Town'), ('Model Town', 'Model Town'), ('Wapda Town', 'Wapda Town'), ('Askari', 'Askari'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Johar Town', 'Johar Town'), ('Ichra', 'Ichra'), ('Canal Road', 'Canal Road')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Both', 'Both'), ('Boys', 'Boys')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, choices=[('Diamond', 'Diamond'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=100),
        ),
    ]
