# Generated by Django 3.2.3 on 2021-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20210806_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Lakshmi Chock', 'Lakshmi Chock'), ('Canal Road', 'Canal Road'), ('Township', 'Township'), ('Johar Town', 'Johar Town'), ('Ichra', 'Ichra'), ('Ferozpur Road', 'Ferozpur Road'), ('Behria Town', 'Behria Town'), ('Iqbal Town', 'Iqbal Town'), ('Model Town', 'Model Town'), ('Jalo', 'Jalo'), ('Thokar', 'Thokar'), ('Askari', 'Askari'), ('Central Park', 'Central Park'), ('Gulberg', 'Gulberg'), ('Valencia Town', 'Valencia Town'), ('Cantt', 'Cantt'), ('Mall Road', 'Mall Road'), ('DHA', 'DHA'), ('Wapda Town', 'Wapda Town'), ('Sadar', 'Sadar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Both', 'Both'), ('Boys', 'Boys'), ('Girls', 'Girls')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Silver', 'Silver')], max_length=100),
        ),
    ]
