# Generated by Django 3.2.3 on 2021-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20210806_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Mall Road', 'Mall Road'), ('Askari', 'Askari'), ('Wapda Town', 'Wapda Town'), ('Canal Road', 'Canal Road'), ('Ferozpur Road', 'Ferozpur Road'), ('Cantt', 'Cantt'), ('Ichra', 'Ichra'), ('Johar Town', 'Johar Town'), ('Gulberg', 'Gulberg'), ('Behria Town', 'Behria Town'), ('Valencia Town', 'Valencia Town'), ('Sadar', 'Sadar'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Township', 'Township'), ('Jalo', 'Jalo'), ('Iqbal Town', 'Iqbal Town'), ('Model Town', 'Model Town'), ('DHA', 'DHA'), ('Thokar', 'Thokar'), ('Central Park', 'Central Park')], max_length=100),
        ),
    ]
