# Generated by Django 3.2.3 on 2021-08-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_listing_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='type',
        ),
        migrations.AddField(
            model_name='listing',
            name='standard',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Gold', 'Gold')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Valencia Town', 'Valencia Town'), ('DHA', 'DHA'), ('Johar Town', 'Johar Town'), ('Behria Town', 'Behria Town'), ('Central Park', 'Central Park'), ('Wapda Town', 'Wapda Town'), ('Ichra', 'Ichra'), ('Model Town', 'Model Town'), ('Gulberg', 'Gulberg'), ('Iqbal Town', 'Iqbal Town'), ('Sadar', 'Sadar'), ('Township', 'Township'), ('Askari', 'Askari'), ('Canal Road', 'Canal Road'), ('Ferozpur Road', 'Ferozpur Road'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Cantt', 'Cantt'), ('Jalo', 'Jalo'), ('Mall Road', 'Mall Road'), ('Thokar', 'Thokar')], max_length=100),
        ),
    ]
