# Generated by Django 3.2.3 on 2021-08-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_auto_20210809_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Mall Road', 'Mall Road'), ('Gulberg', 'Gulberg'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Township', 'Township'), ('Cantt', 'Cantt'), ('DHA', 'DHA'), ('Iqbal Town', 'Iqbal Town'), ('Johar Town', 'Johar Town'), ('Model Town', 'Model Town'), ('Behria Town', 'Behria Town'), ('Jalo', 'Jalo'), ('Sadar', 'Sadar'), ('Central Park', 'Central Park'), ('Valencia Town', 'Valencia Town'), ('Canal Road', 'Canal Road'), ('Ichra', 'Ichra'), ('Thokar', 'Thokar'), ('Wapda Town', 'Wapda Town'), ('Ferozpur Road', 'Ferozpur Road'), ('Askari', 'Askari')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Both', 'Both'), ('Boys', 'Boys')], max_length=100),
        ),
    ]
