# Generated by Django 3.2.3 on 2021-08-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_auto_20210809_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Township', 'Township'), ('Thokar', 'Thokar'), ('Canal Road', 'Canal Road'), ('DHA', 'DHA'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Gulberg', 'Gulberg'), ('Wapda Town', 'Wapda Town'), ('Jalo', 'Jalo'), ('Ichra', 'Ichra'), ('Behria Town', 'Behria Town'), ('Model Town', 'Model Town'), ('Askari', 'Askari'), ('Ferozpur Road', 'Ferozpur Road'), ('Sadar', 'Sadar'), ('Central Park', 'Central Park'), ('Iqbal Town', 'Iqbal Town'), ('Johar Town', 'Johar Town'), ('Mall Road', 'Mall Road'), ('Valencia Town', 'Valencia Town')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Both', 'Both')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='standard',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], max_length=100),
        ),
    ]
