# Generated by Django 3.2.3 on 2021-08-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_auto_20210809_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Askari', 'Askari'), ('Canal Road', 'Canal Road'), ('Behria Town', 'Behria Town'), ('Gulberg', 'Gulberg'), ('Iqbal Town', 'Iqbal Town'), ('Model Town', 'Model Town'), ('Central Park', 'Central Park'), ('Mall Road', 'Mall Road'), ('Thokar', 'Thokar'), ('Valencia Town', 'Valencia Town'), ('Jalo', 'Jalo'), ('DHA', 'DHA'), ('Township', 'Township'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Wapda Town', 'Wapda Town'), ('Ferozpur Road', 'Ferozpur Road'), ('Johar Town', 'Johar Town'), ('Ichra', 'Ichra'), ('Sadar', 'Sadar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Both', 'Both')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='standard',
            field=models.CharField(choices=[('Diamond', 'Diamond'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=100),
        ),
    ]
