# Generated by Django 3.2.6 on 2021-08-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_auto_20210809_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('Mall Road', 'Mall Road'), ('Iqbal Town', 'Iqbal Town'), ('Township', 'Township'), ('Behria Town', 'Behria Town'), ('Central Park', 'Central Park'), ('Ichra', 'Ichra'), ('Gulberg', 'Gulberg'), ('Valencia Town', 'Valencia Town'), ('Askari', 'Askari'), ('Sadar', 'Sadar'), ('Jalo', 'Jalo'), ('DHA', 'DHA'), ('Wapda Town', 'Wapda Town'), ('Johar Town', 'Johar Town'), ('Lakshmi Chock', 'Lakshmi Chock'), ('Thokar', 'Thokar'), ('Canal Road', 'Canal Road'), ('Model Town', 'Model Town'), ('Ferozpur Road', 'Ferozpur Road')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Both', 'Both'), ('Boys', 'Boys'), ('Girls', 'Girls')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='standard',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], max_length=100),
        ),
    ]
